import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";


const geistSans = Kanit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  weight: "100"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
         {children}
      </body>
    </html>
  );
}
